Mini_Prj_/Models/Societe.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Prj_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Societe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Societe()
        {
            this.Abonnements = new HashSet<Abonnement>();
            this.Buses = new HashSet<Bus>();
        }
    
        public int id { get; set; }
        public string adresse { get; set; }
        public string raisonSocial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonnement> Abonnements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Buses { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}

Mini_Prj_/Controllers/BusesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mini_Prj_.Models;

namespace Mini_Prj_.Controllers
{
    public class BusesController : Controller
    {
        private NavetteDB_Entities db = new NavetteDB_Entities();

        // GET: Buses
        public async Task<ActionResult> Index()
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                var buses = db.Buses.Include(b => b.Societe).Include(b => b.Trajet);
                return View(await buses.ToListAsync());
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // GET: Buses/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Bus bus = await db.Buses.FindAsync(id);
                if (bus == null)
                {
                    return HttpNotFound();
                }
                return View(bus);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // GET: Buses/Create
        public ActionResult Create()
        {
            if (Session["UsrSession"] != null)
            {
                string help = "";
                List<SelectListItem> trajets = new List<SelectListItem>();
                ViewBag.UsrSession = Session["UsrSession"];
                ViewBag.idSociete = new SelectList(db.Societes, "id", "RaisonSocial");
                foreach (var t in db.Trajets)
                {
                    help = t.depart + " => " + t.arriver;
                    trajets.Add(new SelectListItem { Text = help, Value = t.id.ToString() });
                }
                ViewBag.idTrajet = trajets;
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // POST: Buses/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,typeDeVehicule,description_,idSociete,idTrajet")] Bus bus)
        {
            if (ModelState.IsValid)
            {
                db.Buses.Add(bus);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.idSociete = new SelectList(db.Societes, "id", "adresse", bus.idSociete);
            ViewBag.idTrajet = new SelectList(db.Trajets, "id", "depart", bus.idTrajet);
            return View(bus);
        }

        // GET: Buses/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Bus bus = await db.Buses.FindAsync(id);
                if (bus == null)
                {
                    return HttpNotFound();
                }
                //ViewBag.idSociete = new SelectList(db.Societes, "id", "RaisonSocial", bus.idSociete);
                string help = "";
                List<SelectListItem> trajets = new List<SelectListItem>();
                ViewBag.idSociete = new SelectList(db.Societes, "id", "RaisonSocial");
                foreach (var t in db.Trajets)
                {
                    help = t.depart + " => " + t.arriver;
                    trajets.Add(new SelectListItem { Text = help, Value = t.id.ToString() });
                }
                var query = (from t in db.Trajets where t.id == bus.idTrajet select t).FirstOrDefault();
                trajets.Find(t => t.Text == query.depart + " => " + query.arriver).Selected = true;
                ViewBag.idTrajet = trajets;
                return View(bus);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // POST: Buses/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,typeDeVehicule,description_,idSociete,idTrajet")] Bus bus)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(bus).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                //ViewBag.idSociete = new SelectList(db.Societes, "id", "RaisonSocial", bus.idSociete);
                string help = "";
                List<SelectListItem> trajets = new List<SelectListItem>();
                //ViewBag.idSociete = new SelectList(db.Societes, "id", "RaisonSocial");
                foreach (var t in db.Trajets)
                {
                    help = t.depart + " => " + t.arriver;
                    trajets.Add(new SelectListItem { Text = help, Value = t.id.ToString() });
                }
                ViewBag.idTrajet = trajets;
                return View(bus);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // GET: Buses/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Bus bus = await db.Buses.FindAsync(id);
                if (bus == null)
                {
                    return HttpNotFound();
                }
                return View(bus);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // POST: Buses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Bus bus = await db.Buses.FindAsync(id);
            db.Buses.Remove(bus);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mini_Prj_/Controllers/TrajetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mini_Prj_.Models;

namespace Mini_Prj_.Controllers
{
    public class TrajetsController : Controller
    {
        private NavetteDB_Entities db = new NavetteDB_Entities();

        // GET: Trajets
        public async Task<ActionResult> Index()
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                return View(await db.Trajets.ToListAsync());
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // GET: Trajets/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Trajet trajet = await db.Trajets.FindAsync(id);
                if (trajet == null)
                {
                    return HttpNotFound();
                }
                return View(trajet);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // GET: Trajets/Create
        public ActionResult Create()
        {
            if (Session["UsrSession"] != null)
            {
                ViewBag.UsrSession = Session["UsrSession"];
                List<SelectListItem> villes = new List<SelectListItem>();
                foreach (var v in db.Villes)
                {
                    villes.Add(new SelectListItem { Text = v.ville1, Value = v.ville1 });
                }
                ViewBag.depart = villes;
                ViewBag.arriver = villes;
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // POST: Trajets/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,depart,arriver,date_depart,date_arriver")] Trajet trajet)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            List<SelectListItem> villes = new List<SelectListItem>();
            foreach (var v in db.Villes)
            {
                villes.Add(new SelectListItem { Text = v.ville1, Value = v.ville1 });
            }
            ViewBag.depart = villes;
            ViewBag.arriver = villes;
            if (ModelState.IsValid)
            {
                db.Trajets.Add(trajet);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(trajet);
        }

        // GET: Trajets/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                List<SelectListItem> villes = new List<SelectListItem>();
                List<SelectListItem> villes2 = new List<SelectListItem>();
                foreach (var v in db.Villes)
                {
                    villes.Add(new SelectListItem { Text = v.ville1, Value = v.ville1 });
                    villes2.Add(new SelectListItem { Text = v.ville1, Value = v.ville1 });
                }
                var query = (from t in db.Trajets where t.id == id select t).FirstOrDefault() ;
                villes.Find(v => v.Text == query.depart).Selected = true;
                villes2.Find(v => v.Text == query.arriver).Selected = true;
                ViewBag.depart = villes;
                ViewBag.arriver = villes2;
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Trajet trajet = await db.Trajets.FindAsync(id);
                if (trajet == null)
                {
                    return HttpNotFound();
                }
                return View(trajet);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // POST: Trajets/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,depart,arriver,date_depart,date_arriver")] Trajet trajet)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            List<SelectListItem> villes = new List<SelectListItem>();
            foreach (var v in db.Villes)
            {
                villes.Add(new SelectListItem { Text = v.ville1, Value = v.ville1 });
            }
            ViewBag.depart = villes;
            ViewBag.arriver = villes;
            if (ModelState.IsValid)
            {
                db.Entry(trajet).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(trajet);
        }

        // GET: Trajets/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (Session["UsrSession"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Trajet trajet = await db.Trajets.FindAsync(id);
                if (trajet == null)
                {
                    return HttpNotFound();
                }
                return View(trajet);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // POST: Trajets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Trajet trajet = await db.Trajets.FindAsync(id);
            db.Trajets.Remove(trajet);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mini_Prj_/Views/Societes/Create.cshtml
@model Mini_Prj_.Models.Societe

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Societe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, "id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adresse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adresse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adresse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.raisonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.raisonSocial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.raisonSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mini_Prj_/Views/Societes/Delete.cshtml
@model Mini_Prj_.Models.Societe

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Societe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.raisonSocial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.raisonSocial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Utilisateur.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Utilisateur.nom)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Mini_Prj_/Views/Societes/Details.cshtml
@model Mini_Prj_.Models.Societe

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Societe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.raisonSocial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.raisonSocial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Utilisateur.nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Utilisateur.nom)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Mini_Prj_/Views/Societes/Edit.cshtml
@model Mini_Prj_.Models.Societe

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Societe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.adresse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adresse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adresse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.raisonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.raisonSocial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.raisonSocial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mini_Prj_/Views/Societes/Index.cshtml
@model IEnumerable<Mini_Prj_.Models.Societe>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.adresse)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.raisonSocial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Utilisateur.nom)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.adresse)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.raisonSocial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Utilisateur.nom)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

Mini_Prj_/Views/Societes/dashboard.cshtml
@{ ViewBag.Title = "dashboard"; }

<div class="container">
    <div class="row justify-content-center">
        <div class="col mt-2">
            <div class="card m-auto" style="width: 18rem;text-align:center">
                <div class="card-body">
                    <h3 class="card-title"><i class="fas fa-bus"></i></h3>
                    <h5 class="card-text">Gérer Bus</h5>
                    <a href="@Url.Action("Index","Buses")" class="btn btn-outline-info">Modifier</a>
                </div>
            </div>
        </div>
        <div class="col mt-2">
            <div class="card m-auto" style="width: 18rem;text-align:center">
                <div class="card-body">
                    <h3 class="card-title"><i class="fas fa-road"></i></h3>
                    <h5 class="card-text">Gérer Trajet</h5>
                    <a href="@Url.Action("Index","Trajets")" class="btn btn-outline-info">Modifier</a>
                </div>
            </div>
        </div>
        <div class="col mt-2">
            <div class="card m-auto" style="width: 18rem;text-align:center">
                <div class="card-body">
                    <h3 class="card-title"><i class="fas fa-book"></i></h3>
                    <h5 class="card-text">Gérer Abonnement</h5>
                    <a href="@Url.Action("Index","Abonnements")" class="btn btn-outline-info">Modifier</a>
                </div>
            </div>
        </div>
        <div class="col mt-2">
            <div class="card m-auto" style="width: 18rem;text-align:center">
                <div class="card-body">
                    <h3 class="card-title"><i class="fas fa-tasks"></i></h3>
                    <h5 class="card-text">Demandes d'Abonnement</h5>
                    <a href="@Url.Action("Index","Demande_Trajet")" class="btn btn-outline-info">Modifier</a>
                </div>
            </div>
        </div>
    </div>
</div>