Mini_Prj_/Controllers/SocietesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mini_Prj_.Models;

namespace Mini_Prj_.Controllers
{
    public class SocietesController : Controller
    {
        private NavetteDB_Entities db = new NavetteDB_Entities();
        //

        public ActionResult dashboard()
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        //
        // GET: Societes
        public async Task<ActionResult> Index()
        {
            if (Session["UsrSession"] != null)
            {
                var societes = db.Societes.Include(s => s.Utilisateur);
                return View(await societes.ToListAsync());
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // GET: Societes/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (Session["UsrSession"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Societe societe = await db.Societes.FindAsync(id);
                if (societe == null)
                {
                    return HttpNotFound();
                }
                return View(societe);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // GET: Societes/Create
        public ActionResult Create()
        {
            if (Session["UsrSession"] != null)
            {
                ViewBag.id = new SelectList(db.Utilisateurs, "id", "nom");
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // POST: Societes/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,adresse,raisonSocial")] Societe societe)
        {
            if (ModelState.IsValid)
            {
                db.Societes.Add(societe);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.id = new SelectList(db.Utilisateurs, "id", "nom", societe.id);
            return View(societe);
        }

        // GET: Societes/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (Session["UsrSession"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Societe societe = await db.Societes.FindAsync(id);
                if (societe == null)
                {
                    return HttpNotFound();
                }
                ViewBag.id = new SelectList(db.Utilisateurs, "id", "nom", societe.id);
                return View(societe);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // POST: Societes/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,adresse,raisonSocial")] Societe societe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(societe).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.id = new SelectList(db.Utilisateurs, "id", "nom", societe.id);
            return View(societe);
        }

        // GET: Societes/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Societe societe = await db.Societes.FindAsync(id);
            if (societe == null)
            {
                return HttpNotFound();
            }
            return View(societe);
        }

        // POST: Societes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Societe societe = await db.Societes.FindAsync(id);
            db.Societes.Remove(societe);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mini_Prj_/Views/Shared/Nav_Bar.cshtml
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
    <a class="navbar-brand" href="@Url.Action("Index","Home")">Navette Express</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index","Home")"><i class="fas fa-home"></i> Acceuil</a>
            </li>
            @if (ViewBag.UsrSession != null && ViewBag.UsrSession.role_ == "client")
            {
                <li class="nav-item">
                      <a class="nav-link" href="@Url.Action("Offres", "Abonnements")"><i class="far fa-newspaper"></i> Offres</a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="@Url.Action("MesAbonnements", "Abonnements")"><i class="fas fa-book-reader"></i> Mes Abonnements</a>
                </li>
                <li class="nav-item">
                     <a class="nav-link" href="@Url.Action("MesDemandes", "Demande_Trajet")"><i class="far fa-paper-plane"></i> Mes Demandes</a>
                </li>
             }
            @if (ViewBag.UsrSession != null && ViewBag.UsrSession.role_ == "societe")
            {
                <li class="nav-item">
                     <a class="nav-link" href="@Url.Action("dashboard", "Societes")"><i class="fas fa-cogs"></i> Dashboard</a>
                </li>            
             }
            @if (ViewBag.UsrSession != null && ViewBag.UsrSession.role_ == "admin")
            {
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Utilisateurs")"><i class="fas fa-cogs"></i> Dashboard</a>
                </li>            
             }
        </ul>
        @if (ViewBag.UsrSession != null)
        {
<ul class="navbar-nav">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="far fa-user-circle"></i> Mon Compte</a>
        <div class="dropdown-menu">
            <h4 class="dropdown-item" style="background-color:#296d98;color:floralwhite"><i class="far fa-user"></i> @ViewBag.UsrSession.nom</h4>
            <div class="dropdown-divider"></div>
            <a href="@Url.Action("Edit", "Utilisateurs", new { id = ViewBag.UsrSession.id})" class="dropdown-item"><i class="far fa-user-circle"></i> Mon Compte</a>
            <div class="dropdown-divider"></div>
            <a href="@Url.Action("sedeconncter","Utilisateurs")" class="dropdown-item"><i class="fas fa-sign-out-alt"></i> Se deconnecter</a>
        </div>
    </li>
</ul>
        }
        @if (ViewBag.UsrSession == null)
        {
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="@Url.Action("Login","Utilisateurs")"><i class="fas fa-user" data-toggle="tooltip" data-placement="bottom" title="Mon compte"></i> Se connecter</a>
    </li>
</ul>
        }
    </div>
</nav>

Mini_Prj_/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous">

    </script>
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    <link rel="stylesheet" href="~/Content/main.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("Nav_Bar")
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>