Mini_Prj_/Models/Demande_Trajet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mini_Prj_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande_Trajet
    {
        public int id { get; set; }
        public string depart { get; set; }
        public string arriver { get; set; }
        public Nullable<System.DateTime> date_depart { get; set; }
        public Nullable<System.DateTime> date_arriver { get; set; }
        public Nullable<int> idUtilisateur { get; set; }
    
        public virtual Client Client { get; set; }
    }
}

Mini_Prj_/Controllers/Demande_TrajetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mini_Prj_.Models;

namespace Mini_Prj_.Controllers
{
    public class Demande_TrajetController : Controller
    {
        private NavetteDB_Entities db = new NavetteDB_Entities();

        //Post DeleteD
        public async Task<ActionResult> DeleteD(int id)
        {
            int idC = int.Parse(Session["Usrid"].ToString());
            var demande = from d in db.Demande_Trajet where d.id == id && d.idUtilisateur == idC select d;
            db.Demande_Trajet.Remove(demande.FirstOrDefault());
            await db.SaveChangesAsync();
            return RedirectToAction("MesDemandes");
        }

        //Get:MesDemandes
        public async Task<ActionResult> MesDemandes()
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                int idC = int.Parse(Session["Usrid"].ToString());
                var check = (from u in db.Utilisateurs where u.id == idC select u).FirstOrDefault();
                if (check.role_=="client")
                {
                    var demande_Trajet = (from d in db.Demande_Trajet where d.idUtilisateur == idC select d);
                    return View(await demande_Trajet.ToListAsync());
                }
                else
                {
                    return RedirectToAction("Login", "Utilisateurs");
                }

            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }
        //
        [HttpPost]
        public async Task<ActionResult> AjouterDemande(int id)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                var query = (from d in db.Demande_Trajet where d.id == id select d).FirstOrDefault();
                var check = (from t in db.Trajets where t.depart==query.depart && t.arriver==query.arriver select t).FirstOrDefault();
                if(check==null)
                {
                    db.Trajets.Add(new Trajet { depart = query.depart, arriver = query.arriver, date_depart = query.date_depart, date_arriver = query.date_arriver });
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // GET: Demande_Trajet
        public async Task<ActionResult> Index()
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                var demande_Trajet = db.Demande_Trajet.Include(d => d.Client);
                return View(await demande_Trajet.ToListAsync());
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // GET: Demande_Trajet/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Demande_Trajet demande_Trajet = await db.Demande_Trajet.FindAsync(id);
                if (demande_Trajet == null)
                {
                    return HttpNotFound();
                }
                return View(demande_Trajet);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // GET: Demande_Trajet/Create
        public ActionResult Create()
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                ViewBag.idUtilisateur = new SelectList(db.Clients, "id", "id");
                List<SelectListItem> villes = new List<SelectListItem>();
                foreach (var v in db.Villes)
                {
                    villes.Add(new SelectListItem { Text = v.ville1, Value = v.ville1 });
                }
                ViewBag.depart = villes;
                ViewBag.arriver = villes;
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // POST: Demande_Trajet/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,depart,arriver,date_depart,date_arriver,idUtilisateur")] Demande_Trajet demande_Trajet)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                if (ModelState.IsValid)
                {
                    db.Demande_Trajet.Add(demande_Trajet);
                    await db.SaveChangesAsync();
                    return RedirectToAction("MesDemandes");
                }

                ViewBag.idUtilisateur = new SelectList(db.Clients, "id", "id", demande_Trajet.idUtilisateur);
                return View(demande_Trajet);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // GET: Demande_Trajet/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Demande_Trajet demande_Trajet = await db.Demande_Trajet.FindAsync(id);
                if (demande_Trajet == null)
                {
                    return HttpNotFound();
                }
                ViewBag.idUtilisateur = new SelectList(db.Clients, "id", "id", demande_Trajet.idUtilisateur);
                return View(demande_Trajet);
            }                
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // POST: Demande_Trajet/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,depart,arriver,date_depart,date_arriver,idUtilisateur")] Demande_Trajet demande_Trajet)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                if (ModelState.IsValid)
                {
                    db.Entry(demande_Trajet).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("MesDemandes");
                }
                ViewBag.idUtilisateur = new SelectList(db.Clients, "id", "id", demande_Trajet.idUtilisateur);
                return View(demande_Trajet);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // GET: Demande_Trajet/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            ViewBag.UsrSession = Session["UsrSession"];
            if (Session["UsrSession"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Demande_Trajet demande_Trajet = await db.Demande_Trajet.FindAsync(id);
                if (demande_Trajet == null)
                {
                    return HttpNotFound();
                }
                return View(demande_Trajet);
            }
            else
            {
                return RedirectToAction("Login", "Utilisateurs");
            }
        }

        // POST: Demande_Trajet/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Demande_Trajet demande_Trajet = await db.Demande_Trajet.FindAsync(id);
            db.Demande_Trajet.Remove(demande_Trajet);
            await db.SaveChangesAsync();
            return RedirectToAction("MesDemandes");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Mini_Prj_/Views/Demande_Trajet/Create.cshtml
@model Mini_Prj_.Models.Demande_Trajet

@{
    ViewBag.Title = "Create";
}

<div class="shadow-lg p-3 mb-5 bg-white w-75 rounded m-auto">
    <div class="row justify-content-center">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Demander un Trajet</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.depart, "depart", htmlAttributes: new { @class = "control -label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("depart", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.depart, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.arriver, "arriver", htmlAttributes: new { @class = "control -label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("arriver", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.arriver, "", new { @class = "text-danger" })
                </div>
            </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.date_depart, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.date_depart, new { htmlAttributes = new { type = "datetime-local", @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.date_depart, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.date_arriver, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.date_arriver, new { htmlAttributes = new { type = "datetime-local", @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.date_arriver, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.idUtilisateur, "idUtilisateur", htmlAttributes: new { @class = "control-label col-md-2", @style = "display:none" })
                    <div class="col-md-10">
                        <input name="idUtilisateur" id="idUtilisateur" value="@ViewBag.UsrSession.id" class="form-control" hidden readonly />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Demander" class="btn w-100 btn-outline-success" />
                    </div>
                </div>
            </div>
        }
    </div>

    <div>
        <a href="@Url.Action("MesDemandes","Demande_Trajet")"><i class="fas fa-arrow-left"></i> Retour à la liste des Demandes</a>
    </div>
</div>

Mini_Prj_/Views/Demande_Trajet/Delete.cshtml
@model Mini_Prj_.Models.Demande_Trajet

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Demande_Trajet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.depart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.depart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.arriver)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.arriver)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_depart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_depart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_arriver)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_arriver)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Client.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Mini_Prj_/Views/Demande_Trajet/Details.cshtml
@model Mini_Prj_.Models.Demande_Trajet

@{
    ViewBag.Title = "Details";
}

<div class="shadow-lg p-3 mb-5 bg-white rounded w-50 m-auto">
    <div class="row justify-content-center">
        <div>
            <h4>Demande_Trajet</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.depart)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.depart)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.arriver)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.arriver)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.date_depart)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.date_depart)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.date_arriver)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.date_arriver)
                </dd>

                <dt>
                    Nom de Client
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Client.Utilisateur.nom) @Html.DisplayFor(model => model.Client.Utilisateur.prenom) 
                </dd>

            </dl>
        </div>
    </div>
    @*<p>
        <a href="@Url.Action("Index","Demande_Trajet")"><i class="fas fa-arrow-left"></i> Retour à la liste des Demandes</a>
    </p>*@
</div>

Mini_Prj_/Views/Demande_Trajet/Edit.cshtml
@model Mini_Prj_.Models.Demande_Trajet

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Demande_Trajet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.depart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.depart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.depart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.arriver, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.arriver, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.arriver, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_depart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_depart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_depart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_arriver, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_arriver, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_arriver, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idUtilisateur, "idUtilisateur", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idUtilisateur", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idUtilisateur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mini_Prj_/Views/Demande_Trajet/Index.cshtml
@model IEnumerable<Mini_Prj_.Models.Demande_Trajet>

@{
    ViewBag.Title = "Index";
}

<h5>
    <i class="fas fa-list-alt"></i> Liste des demandes de Trajet
</h5>
<table class="table table-hover table-responsive-lg" style="max-height: 300px; ">
    <tr class="thead-dark">
        <th>
            @Html.DisplayNameFor(model => model.depart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.arriver)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date_depart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date_arriver)
        </th>
        <th>
            Nom de Client
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.depart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.arriver)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date_depart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.date_arriver)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Client.Utilisateur.nom) @Html.DisplayFor(modelItem => item.Client.Utilisateur.prenom)
            </td>
            <td>
                @using (Html.BeginForm("AjouterDemande", "Demande_Trajet", new { id = item.id }, FormMethod.Post))
                {
                    <a class="fas fa-check-square"></a> <input type="submit" class="btn-link border-0" value="Accpeter" />
                    }|
                @Html.ActionLink("Details", "Details", new { id = item.id })
            </td>
        </tr>
    }

</table>

Mini_Prj_/Views/Demande_Trajet/MesDemandes.cshtml
@model IEnumerable<Mini_Prj_.Models.Demande_Trajet>
@{
    ViewBag.Title = "MesDemandes";
}

<h2 style="text-align:center;">Mes Demandes</h2>
<br />
<p>
    <i class="fas fa-paper-plane"></i>
    @Html.ActionLink("Envoyer une Demande", "Create")
</p>
<div class="shadow-lg p-3 mb-5 bg-white rounded m-auto">
    <div class="row justify-content-center">
        <div class="table-responsive">
            <table class="table table-hover w-100 m-auto" style="max-height:400px">
                @if (Model != null)
                {
                    <tr class="thead-dark">
                        <th>
                            @Html.DisplayNameFor(model => model.depart)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.arriver)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.date_depart)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.date_arriver)
                        </th>
                        <th>
                            Nom de Client
                        </th>
                        <th></th>
                    </tr>
                    foreach (var c in Model)
                    {
                        <tr>
                            <td style="vertical-align: middle;"><h5>@c.depart</h5></td>
                            <td style="vertical-align: middle;"><h5>@c.arriver</h5></td>
                            <td style="vertical-align: middle;"><h5>@c.date_depart</h5></td>
                            <td style="vertical-align: middle;"><h5>@c.date_arriver</h5></td>
                            <td style="vertical-align: middle;"><h5>@c.Client.Utilisateur.nom</h5></td>
                            <td style="vertical-align: middle;">
                                <i class="fas fa-info-circle"></i>
                                @Html.ActionLink("Details", "Details", new { id = c.id }) |

                                <a class="btn btn-outline-danger btn-sm passingID" data-toggle="modal" data-target="#exampleModal" data-id="@c.id">
                                    <i class="fas fa-trash"></i> Supprimer
                                </a>

                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal" onshow="" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Suppression!</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>Etes vous sur de supprimer cette demande?</p>
                                                <input id="id_" type="text" hidden readonly />
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="button" class="btn btn-outline-danger" onclick="f1()">Supprimer</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>

                        </tr>
                    }
                }
                @if (Model == null)
                {
                    <tr><td style="text-align:center;"><h5>Aucune resultat trouvé</h5></td></tr>
                }
            </table>
        </div>
    </div>
</div>

<script>
    var id = document.getElementById("id_");
    $(document).on("click", ".passingID", function () {
        var ids = $(this).attr('data-id');
        id.value = ids;
    });
    function f1() {
        window.location.href = "https://localhost:44344/Demande_Trajet/DeleteD/" + id.value;
    }
</script>